import Header from "./Header";
import Hero from "./Hero";
import { Card } from "./Card";
import Footer from "./Footer";
import Contact from "./Contact";
import Gallery from "./Gallery";
import AllDestinations from "./AllDestinations";
import Services from "./Services";
import Destinations from "./Destinations";
import Testimonials from "./Testimonials";
import AdminTrekForm from "./AdminTrekForm";
import SignInForm from "./SignInForm";
import SignUpForm from "./SignUpForm";
import DestinationDetails from "./DestinationDetails";
import BookingForm from "./BookingForm";
import AdminPanel from "./AdminPanel";
import EditTrekForm from "./EditTrekForm";
import { checkUserAuthLoader,checkAdminAuthLoader } from "./checkAuthLoader";
import Unauthorized from "./Unauthorized";

export { Header, Hero, Card, Footer, Destinations,Contact, Gallery, AllDestinations, Services, Testimonials, AdminTrekForm, EditTrekForm, SignInForm, SignUpForm , DestinationDetails , BookingForm, AdminPanel,checkAdminAuthLoader,checkUserAuthLoader,Unauthorized};
